### PR TITLE
Color fields as color picker

### PR DESCRIPTION
**Pull request by cristineguadelupe**
Screen Shot 2022-07-05 at 17 21 01

### CODE REVIEW

**Comment by jonatanklosko** [comment]
What if we showed all colors as squares?

**Comment by cristineguadelupe** [comment]
> What if we showed all colors as squares?

Without the border radius, you mean?
Screen Shot 2022-07-05 at 17 44 45

**Comment by jonatanklosko** [comment]
I mean using the same width and height for each color box :)

**Comment by josevalim** [comment]
@jonatanklosko i think the square is not going to work out once we add the grid and make each input use some consistent amount of spacing.

**Comment by cristineguadelupe** [comment]
Ignore the labels for now...
Looks too small imo...
Screen Shot 2022-07-05 at 17 51 02

**Comment by cristineguadelupe** [comment]
Anyway, we can try some variations when changing to grid. Wdyt?

**Comment by jonatanklosko** [comment]
@josevalim the color box doesn't need to be full width in that case either, no?

@cristineguadelupe I like that version, just needs ` white-space: nowrap` on the label. I think the initial rectangles are fine too, but I would make the single color the same width as the other ones. Whatever you like more :)

**Comment by cristineguadelupe** [comment]
An option to mitigate mis click/touch is to add some space
Screen Shot 2022-07-05 at 18 00 54

**Comment by jonatanklosko** [comment]
I think it looks better glued together. The squares seems big enough to me, but if you're concerned with misclicks then use the width from the initial version :)

**Comment by josevalim** [comment]
Let's go with any version for now... we can decide once we have the grid layout. :)

**Comment by cristineguadelupe** [comment]
> I think it looks better glued together. The squares seem big enough to me, but if you're concerned with misclicks then use the width from the initial version :)

I also like it glued together! Well, I'll keep the current version and we'll decide later on

**Review by josevalim — APPROVED** [review]

**Pull request merged**
